Navbar is in Progress and React app is initialised
kalviumcommunity/gamedex pull request #1
Opened 2023-02-23 06:39 UTC by Saksham091

2023-02-24 15:07 UTC, aditya-190 requested changes
Congratulations for your First PR. Pls make the required changes and you are then ready to merge the changes.

2023-02-24 15:07 UTC, aditya-190 commented on client/README.md
> +
Update the README file to have some description about your project and it can also be used to track your progress too. Checkout this for reference -> https://github.com/kalviumcommunity/openbadgx/blob/main/README.md

2023-02-24 15:07 UTC, aditya-190 commented on client/package.json
> +  "name": "client",
Update the name to be -> gamedex_client

2023-02-24 15:07 UTC, aditya-190 commented on client/package.json
> +    "i": "^0.3.7",
testing libraries can be added in devDependecies and I think the library "i" is mistakenly added, you can remove this.

2023-02-24 15:07 UTC, aditya-190 commented on client/public/index.html
> +    <title>React App</title>
Add your Project name -> GameDex

2023-02-24 15:07 UTC, aditya-190 commented on client/public/manifest.json
> +      "src": "logo192.png",
These logos can be removed.

2023-02-24 15:07 UTC, aditya-190 commented on client/public/manifest.json
> +  "name": "Create React App Sample",
Add a name of your project.

2023-02-24 15:07 UTC, aditya-190 commented on server/package.json
> +  "name": "server",
name can be changed as -> gamedex_server or gamedex_backend

2023-02-25 04:31 UTC, PatelNeelMahesh requested changes

2023-02-25 04:31 UTC, PatelNeelMahesh commented on client/package.json
> +    "i": "^0.3.7",
You can uninstall "i" package from package.json.
Use npm install/ npm i to initialize the react app.
npm install i -> means install "i" package.

2023-02-25 04:31 UTC, PatelNeelMahesh commented on client/README.md
> +# Getting Started with Create React App
Update the default readme file with your capstone description and add topics covered with links to the PR.

2023-02-27 07:02 UTC, Saksham091 commented on client/README.md
> +
Done

2023-02-27 07:03 UTC, Saksham091 commented on client/package.json
> +  "name": "client",
Done

2023-02-27 07:04 UTC, Saksham091 commented on client/package.json
> +    "i": "^0.3.7",
Done

2023-02-27 07:04 UTC, Saksham091 commented on client/public/index.html
> +    <title>React App</title>
Done

2023-02-27 07:44 UTC, PatelNeelMahesh reviewed
You need to act on given feedback and then you should merge pull request.

2023-02-28 06:11 UTC, Saksham091 commented on client/public/manifest.json
> +      "src": "logo192.png",
done

2023-02-28 06:11 UTC, Saksham091 commented on client/package.json
> +    "i": "^0.3.7",
done

2023-02-28 06:12 UTC, Saksham091 commented on server/package.json
> +  "name": "server",
done

2023-02-28 06:13 UTC, Saksham091 commented on client/public/manifest.json
> +  "name": "Create React App Sample",
done

2023-02-28 06:13 UTC, Saksham091 commented on client/README.md
> +# Getting Started with Create React App
done

2023-03-01 07:46 UTC, PatelNeelMahesh requested changes
<img width="796" alt="image" src="https://user-images.githubusercontent.com/77996149/222075831-44b932e1-b7a0-47f1-81c0-176d20583519.png">

Before pushing new changes, merge pull request, here you need to merge pull request, then push code to your repo and raise new pull request.

2023-03-03 06:23 UTC, merged